### ISSUE TITLE
Error pip3 install py-zabbix ruamel.yaml

### ISSUE THREAD

**Issue by jeffersonjcd** [Prototype-X/Zabbix-Network-Weathermap#10]
Hi Prototype-X,

When I try to execute command pip3 install py-zabbix ruamel.yaml, occur this error, can you help me?

RuntimeError: dictionary changed size during iteration

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-ky53jlkq/ruamel.yaml
Storing debug log for failure in /root/.pip/pip.log

--- end of log ---

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-ky53jlkq/ruamel.yaml
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1230, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python3/dist-packages/pip/req.py", line 326, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python3/dist-packages/pip/util.py", line 716, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-ky53jlkq/ruamel.yaml

**Comment by Prototype-X** [comment]
Hi, jeffersonjcd
https://pypi.python.org/pypi/ruamel.yaml
Support version python 3.3, 3.4, 3.5
What is your version of Python?

If you have correct version of Python try this:
`pip3 install ruamel.yaml==0.11.7`

**Comment by jeffersonjcd** [comment]
Hi,  Prototype-X 

I,m with Pythn in version 3.4.2.

Thanks

**Comment by jeffersonjcd** [comment]
Prototype-X,

I found this informations,

root@ZPECESRVZABBIX01:/usr/bin# ls -la python*
lrwxrwxrwx 1 root root       9 Dec 27 10:06 python -> python3.4
lrwxrwxrwx 1 root root       9 Mar 16  2015 python2 -> python2.7
-rwxr-xr-x 1 root root 3785928 Mar  1  2015 python2.7
lrwxrwxrwx 1 root root       9 Nov 30  2014 python3 -> python3.4
lrwxrwxrwx 1 root root      16 Nov 30  2014 python3-config -> python3.4-config
-rwxr-xr-x 2 root root 4476488 Oct  8  2014 python3.4
lrwxrwxrwx 1 root root      33 Oct  8  2014 python3.4-config -> x86_64-linux-gnu-python3.4-config
-rwxr-xr-x 2 root root 4476488 Oct  8  2014 python3.4m
lrwxrwxrwx 1 root root      34 Oct  8  2014 python3.4m-config -> x86_64-linux-gnu-python3.4m-config
lrwxrwxrwx 1 root root      10 Nov 30  2014 python3m -> python3.4m
lrwxrwxrwx 1 root root      17 Nov 30  2014 python3m-config -> python3.4m-config
root@ZPECESRVZABBIX01:/usr/bin#

**Comment by Prototype-X** [comment]
run
`pip3 install ruamel.yaml==0.11.7`

**Comment by jeffersonjcd** [comment]
Thanks my friend.

All ok.

**Comment by jeffersonjcd** [comment]
Hi Prototype-X,

My Friend, after to execute all the step by step, my alerts of telegram stopped, can you help me?
