### ISSUE TITLE
can update host 

### ISSUE THREAD

**Issue by empereira** [Prototype-X/Zabbix-Network-Weathermap#14]
Hello Prototype-X, thank you for the great work on zabbix-network-weathermap!! :+1: 

There is an error in the attached image when I try to add the template to the host. The host in question is a switch monitored via snmp.
![error](https://user-images.githubusercontent.com/29874574/27966216-d6378dd6-6314-11e7-960e-b281ffd796bb.png)

Does the template only work on hosts with zabbix-agent installed? If so, how do I use weathermap with switchs/routers?

**Comment by Prototype-X** [comment]
Hi
Yes, template only work on hosts with zabbix-agent installed.
This template need for run scripts weathermap on host, where weathermap installed or you can run scripts with cron/systemd/manually.
Do not use a template to each host (switch/router)
Add template to zabbix server host only.

**Comment by empereira** [comment]
I was suspecting that. Thanks for the feedback.

**Comment by empereira** [comment]
Hello,

When adding a link, the error below occurs.

root@zabbix:/opt/Zabbix-Network-Weathermap# ./weathermap.py -m mapname1.yaml -i /var/www/
Traceback (most recent call last):
  File "./weathermap.py", line 121, in <module>
    main()
  File "./weathermap.py", line 118, in main
    WeathermapCLI()
  File "./weathermap.py", line 53, in __init__
    self._map_img()
  File "./weathermap.py", line 95, in _map_img
    map_obj = cfg.create_map(self.font_path_fn, self.icon_path)
  File "/opt/Zabbix-Network-Weathermap/config.py", line 161, in create_map
    data_in, data_out = self.zbx.get_item_data2(hostname, item_in, item_out)
  File "/opt/Zabbix-Network-Weathermap/zabbix.py", line 43, in get_item_data2
    hostid = self.zbx_api.host.get(filter={'name': hostname}, output='shorten')[0]['hostid']
IndexError: list index out of range

**yaml map:**
...
node-1:
  name: SWTSCORE1
  label: SWTSCORE1
  icon: Router64.png
  x: 625
  y: 225
node-2:
  name: SW01LA1002
  label: SW01LA1002
  icon: Router64.png
  x: 500
  y: 100
link-1:
  node1: node-1
  node2: node-2
  name1: ''
  name2: ''
  hostname: ''
  itemin: ifInOctets[gigabitethernet10]
  itemout: ifOutOctets[gigabitethernet10]
...

In name1, name2 and hostname do I need to set something?

**Comment by Prototype-X** [comment]
Hi,
Where is hostname? Hostname not set on link-1.

**Comment by empereira** [comment]
Hostname for node-1 or node-2 I put there? Or another hostname?

**Comment by Prototype-X** [comment]
link-1:
node1: node-1
node2: node-2
name1: ''
name2: ''
**hostname: '' <-- it hostname )))**
itemin: ifInOctets[gigabitethernet10]
itemout: ifOutOctets[gigabitethernet10]

**Comment by empereira** [comment]
Ok, but what hostname I put there? Hostname from node-1 or node-2?

**Ex:**
link-1:
node1: node-1
node2: node-2
name1: ''
name2: ''
hostname: SWTSCORE1 <<<< hostname from node-1 _**This is correct?**_
itemin: ifInOctets[gigabitethernet10]
itemout: ifOutOctets[gigabitethernet10]

In name1 and name2 what I put?

Another error appear in weathermap.scan.map[{$SCANMAP}] See in attach.
![error](https://user-images.githubusercontent.com/29874574/27996537-a84be348-64ba-11e7-8a9f-26669a1738af.png)

**Comment by Prototype-X** [comment]
If host SWTSCORE1 have item key ifInOctets[gigabitethernet10] and ifOutOctets[gigabitethernet10] then correctly.
> Another error appear in weathermap.scan.file[{$SCANFILE}].

Weathermap dont have permission for write to file mapname1.yaml.

**Comment by empereira** [comment]
Here the permissions.

root@zabbix:/opt/Zabbix-Network-Weathermap# ls -lah
total 164K
drwxr-xr-x 10 zabbix zabbix 4.0K Jul  9 14:57 .
drwxr-xr-x 11 root   root   4.0K Jul  8 16:23 ..
-rwxr-xr-x  1 zabbix zabbix  18K Jun 28 21:06 config.py
-rwxr-xr-x  1 zabbix zabbix  13K Jun 28 21:06 converter.py
drwxr-xr-x  2 zabbix zabbix 4.0K Jun 28 21:06 fonts
drwxr-xr-x  8 zabbix zabbix 4.0K Jun 28 21:06 .git
drwxr-xr-x  2 zabbix zabbix 4.0K Jun 28 21:06 icons
-rw-r--r--  1 zabbix zabbix  35K Jun 28 21:06 LICENSE
drwxr-xr-x  2 zabbix zabbix 4.0K Jul  9 15:53 mapcfgs
drwxr-xr-x  2 zabbix zabbix 4.0K Jul  7 13:15 mapimgs
-rwxr-xr-x  1 zabbix zabbix  14K Jun 28 21:06 mapping.py
drwxr-xr-x  2 zabbix zabbix 4.0K Jul  7 11:43 __pycache__
-rw-r--r--  1 zabbix zabbix 7.7K Jun 28 21:06 README.md
-rw-r--r--  1 zabbix zabbix   38 Jun 28 21:06 requirements.txt
-rwxr-xr-x  1 zabbix zabbix  376 Jun 28 21:06 starter.py
drwxr-xr-x  2 zabbix zabbix 4.0K Jun 28 21:06 template
drwxr-xr-x  2 zabbix zabbix 4.0K Jun 28 21:06 tests
-rw-r--r--  1 zabbix zabbix  413 Jun 28 21:06 TODO
-rwxr-xr-x  1 zabbix zabbix 4.5K Jun 28 21:06 weathermap.py
-rwxr-xr-x  1 zabbix zabbix 5.9K Jun 28 21:06 zabbix.py
root@zabbix:/opt/Zabbix-Network-Weathermap# cd mapcfgs/
root@zabbix:/opt/Zabbix-Network-Weathermap/mapcfgs# ls -lah
total 24K
drwxr-xr-x  2 zabbix zabbix 4.0K Jul  9 15:53 .
drwxr-xr-x 10 zabbix zabbix 4.0K Jul  9 14:57 ..
-rw-r--r--  1 zabbix zabbix 1.1K Jun 28 21:06 example.cfg
-rw-r--r--  1 zabbix zabbix 1.1K Jun 28 21:06 example.yaml
**-rwxrwxrwx  1 zabbix zabbix  809 Jul  9 15:53 mapname1.yaml**
-rw-r--r--  1 root   root    809 Jul  9 15:10 mapname1.yaml.bkp

It's correct?

**Comment by Prototype-X** [comment]
it's ok

**Comment by empereira** [comment]
Ok.

link-1:
  node1: node-1
  node2: node-2
  name1: ''             # For human readability, get from zabbix
  name2: ''             # For human readability, get from zabbix
  hostname: SWTSCORE1 **<<<<<<<<<<<<<<<**
  itemin: ifInOctets[gigabitethernet10]
  itemout: ifOutOctets[gigabitethernet10]

When I put the hostname as SWTSCORE1 the errors below occur.

File "/opt/Zabbix-Network-Weathermap/config.py", line 161, in create_map
data_in, data_out = self.zbx.get_item_data2(hostname, item_in, item_out)
File "/opt/Zabbix-Network-Weathermap/zabbix.py", line 43, in get_item_data2
hostid = self.zbx_api.host.get(filter={'name': hostname}, output='shorten')[0]['hostid']
**IndexError: list index out of range**

Item key ifOutOctets[gigabitethernet10] for SWTSCORE1. The **ifInOctets** is also correct.
![item_key](https://user-images.githubusercontent.com/29874574/27999218-14c93e0e-64f1-11e7-8182-8e754bc8886f.png)

**Comment by Prototype-X** [comment]
Run script manually add option -d (--debug) and show me output

**Comment by empereira** [comment]
Output:

root@zabbix:/opt/Zabbix-Network-Weathermap# ./weathermap.py -d -m poa.yaml -i /var/www/
[10/07/2017 15:53:42] [config:DEBUG] - Object singleton ConfigTemplate created
[10/07/2017 15:53:42] [config:DEBUG] - Config check: Ok
[10/07/2017 15:53:42] [pyzabbix.api:DEBUG] - ZabbixAPI.login(weathermap,p4$$wdblah)
[10/07/2017 15:53:42] [pyzabbix.api:DEBUG] - Call user.login method
[10/07/2017 15:53:42] [pyzabbix.api:DEBUG] - urllib2.Request(https://zbx.example.com/api_jsonrpc.php, {"id": "1", "params": {"user": "weathermap", "password": "p4$$wdblah"}, "jsonrpc": "2.0", "method": "user.login"})
[10/07/2017 15:53:42] [pyzabbix.api:DEBUG] - Response Body: {
    "result": "b55944104d627ac2c54de779c5708f2a",
    "id": "1",
    "jsonrpc": "2.0"
}
[10/07/2017 15:53:42] [pyzabbix.api:DEBUG] - JSON-PRC Server: https://zbx.example.com/api_jsonrpc.php
[10/07/2017 15:53:42] [zabbix:DEBUG] - Object ZabbixAgent created
[10/07/2017 15:53:42] [pyzabbix.api:DEBUG] - Call apiinfo.version method
[10/07/2017 15:53:42] [pyzabbix.api:DEBUG] - urllib2.Request(https://zbx.example.com/api_jsonrpc.php, {"id": "1", "params": {}, "jsonrpc": "2.0", "method": "apiinfo.version"})
[10/07/2017 15:53:42] [pyzabbix.api:DEBUG] - Response Body: {
    "result": "3.2.5",
    "id": "1",
    "jsonrpc": "2.0"
}
[10/07/2017 15:53:42] [zabbix:DEBUG] - API ver. 3.2.5
[10/07/2017 15:53:42] [config:DEBUG] - Config loaded
[10/07/2017 15:53:42] [config:DEBUG] - Object ConfigLoader created
[10/07/2017 15:53:42] [mapping:DEBUG] - Object Label created
[10/07/2017 15:53:42] [mapping:DEBUG] - Object Node created
[10/07/2017 15:53:42] [mapping:DEBUG] - Object Label created
[10/07/2017 15:53:42] [mapping:DEBUG] - Object Node created
[10/07/2017 15:53:42] [mapping:DEBUG] - Object Link created
[10/07/2017 15:53:42] [pyzabbix.api:DEBUG] - Call host.get method
[10/07/2017 15:53:42] [pyzabbix.api:DEBUG] - urllib2.Request(https://zbx.example.com/api_jsonrpc.php, {"id": "1", "params": {"filter": {"name": "SWTSCORE1"}, "output": "shorten"}, "jsonrpc": "2.0", "method": "host.get", "auth": "b55944104d627ac2c54de779c5708f2a"})
[10/07/2017 15:53:42] [pyzabbix.api:DEBUG] - Response Body: {
    "result": [],
    "id": "1",
    "jsonrpc": "2.0"
}
Traceback (most recent call last):
  File "./weathermap.py", line 121, in <module>
    main()
  File "./weathermap.py", line 118, in main
    WeathermapCLI()
  File "./weathermap.py", line 53, in __init__
    self._map_img()
  File "./weathermap.py", line 95, in _map_img
    map_obj = cfg.create_map(self.font_path_fn, self.icon_path)
  File "/opt/Zabbix-Network-Weathermap/config.py", line 161, in create_map
    data_in, data_out = self.zbx.get_item_data2(hostname, item_in, item_out)
  File "/opt/Zabbix-Network-Weathermap/zabbix.py", line 43, in get_item_data2
    hostid = self.zbx_api.host.get(filter={'name': hostname}, output='shorten')[0]['hostid']
IndexError: list index out of range

**Comment by Prototype-X** [comment]
User "weathermap" has read or read-write access to host SWTSCORE1?
Try with admin account.

**Comment by empereira** [comment]
have permissions like "zabbix super admin".

**Comment by Prototype-X** [comment]
![wtf10](https://user-images.githubusercontent.com/12714643/28040087-43ed3712-65cd-11e7-9dd9-6f2eaf039d2d.png)
Hostname is SWTSCORE1 really? Are you sure?

**Comment by empereira** [comment]
This is "**visible name**" option
![hostname](https://user-images.githubusercontent.com/29874574/28040420-2313f124-659c-11e7-8704-880ac68d0d49.png)

Edit:

That was the problem!!! O.o

I thought it did not influence the hostname and visible name!! Sorry for the inconvenience!! :D

**Comment by Prototype-X** [comment]
Find problem. I dont use visible names. When visible name set, try use visible name instead hostname.
`'SWTSCORE1 (NOC)'`

**Comment by empereira** [comment]
In the README screenshot you are clicking on the switch icon and it is showing some options. I can not do this in mine. Any extra setup?

**Comment by Prototype-X** [comment]
1. Create map in zabbix minimum two hosts and one link 
2. Save map
3. Use last release weathermap 1.1.3
4. Scan map `weathermap.py -s mapname1  -z http://zabbix.example.ru -l login -p password`
5. Upload image to zabbix `weathermap.py -m mapname1.yaml -u`
6. Set Zabbix -> Monitoring -> Maps -> mapname1 -> Properties -> Background image -> mapname1
7. Open map mapname1  Zabbix -> Monitoring -> Maps -> mapname1
8. Set in file mapname1.yaml hostname and itemin and itemout only.

**Comment by empereira** [comment]
Thanks for all of your help Prototype-X!!! :D 
Solved!!!

**Comment by psmartins** [comment]
Dear Prototype-X

How do I decrease the width of the links between hosts? I generated the map, but the arrows were disproportionately large.

Thank you for your help.

**Comment by Prototype-X** [comment]
1. Open file /opt/Zabbix-Network-Weathermap/mapcfgs/mapname.yaml
2. find link
3. add width statement
```
link-1:
      node1: node-Router
      node2: node-Switch
      name1: R1
      name2: SW1
      width: 7
```

**Comment by psmartins** [comment]
Thanks !
