### ISSUE TITLE
Curved Links

### ISSUE THREAD

**Issue by gusttavosouza** [Prototype-X/Zabbix-Network-Weathermap#21]
Good Morning!!
I was able to install and integrate with zabbix and would like to congratulate the project very very good. I have a problem, I need to make the curved links, how?

I searched the weathermap site and found 

`VIA x-coord y-coord`
`VIASTYLE curved`

I do not know if it works here either?

**Comment by Prototype-X** [comment]
Hi
Curved link not supported.
Perhaps in future releases this functionality will be implemented.

**Comment by gusttavosouza** [comment]
Ok, Thanks!
