### ISSUE TITLE
Get Data with spaces in item name

### ISSUE THREAD

**Issue by beye91** [Prototype-X/Zabbix-Network-Weathermap#22]
Hi,
when I try to get data from items with a space I get the following error:

>     raise ZbxException('item: {} not found'.format(item_in))
> zabbix.ZbxException: item: reth1.0 - Inbound traffic not found

Is it possible to get data with spaces in item names?

**Comment by Prototype-X** [comment]
Hi,
> zabbix.ZbxException: item: reth1.0 - Inbound traffic not found

Use item key, not name.

> Is it possible to get data with spaces in item names?

Get data with item names not possible.

**Comment by beye91** [comment]
Hi, thanks! :)
