### ISSUE TITLE
Show data traffic below 1Mbps on the map

### ISSUE THREAD

**Issue by psmartins** [Prototype-X/Zabbix-Network-Weathermap#29]
Hi Maxim,

I would like to know what change I have to do in the mapping.py file so that the values ​​when the data traffic on the link is below 1Mbps show on the on the map as below example:

Data traffic 300 Kbps - display 300K on the map. Currently 0.3M is shown.

It's possible ?

Thank you

**Comment by Prototype-X** [comment]
Download last source code.

**Comment by Prototype-X** [comment]
Download last source code.

**Comment by Prototype-X** [comment]
Download last source code.

**Comment by psmartins** [comment]
Thanks
