### ISSUE TITLE
/etc/zabbix/zabbix_agentd.d/ not found

### ISSUE THREAD

**Issue by alphaonex86** [Prototype-X/Zabbix-Network-Weathermap#7]
Hello,

cp /opt/Zabbix-Network-Weathermap/template/userparameter_weathermap.conf /etc/zabbix/zabbix_agentd.d/, faIl because /etc/zabbix/zabbix_agentd.d/ not exists. I use zabbix 3.2 under gentoo.

Cheers,

**Comment by Prototype-X** [comment]
Hi,
open /etc/zabbix/zabbix_agentd.conf and find section:
`### Option: Include`
`#       You may include individual files or all files in a directory in the configuration file.`
`#       Installing Zabbix will create include directory in /usr/local/etc, unless modified during the compile  time.`
`#`
`# Mandatory: no`
`# Default:`
`# Include=`
` `
`Include=/etc/zabbix/zabbix_agentd.d/`
` `
`# Include=/usr/local/etc/zabbix_agentd.userparams.conf`
`# Include=/usr/local/etc/zabbix_agentd.conf.d/`
`# Include=/usr/local/etc/zabbix_agentd.conf.d/*.conf`

copy userparameter_weathermap.conf to dir specified in the option "Include"
