### ISSUE TITLE
zabbix.ZbxException: image name not found

### ISSUE THREAD

**Issue by alphaonex86** [Prototype-X/Zabbix-Network-Weathermap#8]
I'm at this level into the README (I have remplaced the correct arguements):
weathermap.py -s mapname1 mapnameN -z http://zabbix.example.com -l admin -p admin
I'm beginner to zabbi 3.2. I'm blocked on:
Traceback (most recent call last):
  File "/opt/Zabbix-Network-Weathermap/weathermap.py", line 121, in <module>
    main()
  File "/opt/Zabbix-Network-Weathermap/weathermap.py", line 118, in main
    WeathermapCLI()
  File "/opt/Zabbix-Network-Weathermap/weathermap.py", line 55, in __init__
    self._map_scan()
  File "/opt/Zabbix-Network-Weathermap/weathermap.py", line 69, in _map_scan
    scan_map.create()
  File "/opt/Zabbix-Network-Weathermap/config.py", line 230, in create
    nodename = self.dict_call[int(node['elementtype'])](node['elementid'])
  File "/opt/Zabbix-Network-Weathermap/zabbix.py", line 141, in get_imagename
    raise ZbxException('image name not found')
zabbix.ZbxException: image name not found

**Comment by alphaonex86** [comment]
NOTE into the README:
- Open file mapname1.yaml and set hostname and itemin, itemout.
  Into:
- Open file mapname1.yaml and set hostname and itemin, itemout. (the file is into /opt/Zabbix-Network-Weathermap/mapcfgs/)
  Edit the itemin, how? I not understand item key name

**Comment by Prototype-X** [comment]
> zabbix.ZbxException: image name not found

On your  zabbix map exist image, this map elements not support. But now it's fixed. Download the latest version of source code.

**Comment by Prototype-X** [comment]
> (the file is into /opt/Zabbix-Network-Weathermap/mapcfgs/)

yes

> Edit the itemin, how? I not understand item key name

You can read this: https://www.zabbix.com/documentation/3.2/manual/config/items

For example: zabbix-> Configuration -> Templates -> Template SNMP Interfaces -> Discovery rules -> Item prototypes -> key column
name |                                                                     key
Incoming traffic on interface {#SNMPVALUE}     |   ifInOctets[{#SNMPVALUE}]
Outgoing traffic on interface {#SNMPVALUE}     |   ifOutOctets[{#SNMPVALUE}]

In mapname1.yaml itemin/itemout it key with bandwidth data  ifInOctets[{#SNMPVALUE}] or ifOutOctets[{#SNMPVALUE}]

This is only an example, for use this you need assign template to host (for example: sw1) and
zabbix -> Configuration -> Hosts -> sw1 -> Items -> key column.

**Comment by alphaonex86** [comment]
All this explication can be useful into the README

**Comment by GithBM** [comment]
Add the same problem with "zabbix.ZbxException: image name not found" after trying the first time scan map.
I figured out that the {$SCANMAP} function don't like "image" as icon on the Zabbix Map.

**Comment by Prototype-X** [comment]
Hi Saki0
You are using the latest version of the source code (not release)?
Because I don't have this problem.

**Comment by GithBM** [comment]
I wasn't using the source code, was on release 1.1.
I saw that you have done a new release with the source code thank you, it's easier for me to download it.
Problem solved, image items are now understood by your code.
Thanks
